# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RunnerGuard < Formula
  desc "CI/CD source-to-sink vulnerability scanner for GitHub Actions"
  homepage "https://github.com/Vigilant-LLC/runner-guard"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v0.2.0/runner-guard_0.2.0_darwin_amd64.tar.gz"
      sha256 "890ea1d8ef2e14e32b322cafe3b219e7af1d4a3f405123828f8717390cd40cc5"

      define_method(:install) do
        bin.install "runner-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v0.2.0/runner-guard_0.2.0_darwin_arm64.tar.gz"
      sha256 "a6631cf7575def06ad95b5bd86cfc0d315e8e1049c4e38c184114a57558af836"

      define_method(:install) do
        bin.install "runner-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v0.2.0/runner-guard_0.2.0_linux_amd64.tar.gz"
      sha256 "0ac58fc54fae75b6833871c3f479e8d538678af3a32b5299a372d13e3ed6e170"
      define_method(:install) do
        bin.install "runner-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v0.2.0/runner-guard_0.2.0_linux_arm64.tar.gz"
      sha256 "e216f90385e511a14c7147a42dfecd5082bbb8b531daeeae0dd385a76f177fac"
      define_method(:install) do
        bin.install "runner-guard"
      end
    end
  end

  test do
    system "#{bin}/runner-guard", "version"
  end
end
