# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vxpwngard < Formula
  desc "CI/CD source-to-sink vulnerability scanner for GitHub Actions"
  homepage "https://github.com/Vigilant-LLC/vxpwngard"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vigilant-LLC/vxpwngard/releases/download/v0.1.0/vxpwngard_0.1.0_darwin_amd64.tar.gz"
      sha256 "63f880411a1862ebfbcb2568c9f2afeb07288b6815a938837f9a6bb3035d0875"

      define_method(:install) do
        bin.install "vxpwngard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vigilant-LLC/vxpwngard/releases/download/v0.1.0/vxpwngard_0.1.0_darwin_arm64.tar.gz"
      sha256 "e071c4b630fddaa4c36ff4a83233c0dd142d8d74caa3694bb4963bbc428e7311"

      define_method(:install) do
        bin.install "vxpwngard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/vxpwngard/releases/download/v0.1.0/vxpwngard_0.1.0_linux_amd64.tar.gz"
      sha256 "873580a342bae72dbcc2a8e20f6a761365f4904a26ee9996861478c4d7a64cb1"
      define_method(:install) do
        bin.install "vxpwngard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/vxpwngard/releases/download/v0.1.0/vxpwngard_0.1.0_linux_arm64.tar.gz"
      sha256 "9d0eee3163d766c105ed8bf517a8e06ff0684d3a470542a44d1fd857324b378c"
      define_method(:install) do
        bin.install "vxpwngard"
      end
    end
  end

  test do
    system "#{bin}/vxpwngard", "version"
  end
end
