# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RunnerGuard < Formula
  desc "CI/CD source-to-sink vulnerability scanner for GitHub Actions"
  homepage "https://github.com/Vigilant-LLC/runner-guard"
  version "2.4.1"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v2.4.1/runner-guard_2.4.1_darwin_amd64.tar.gz"
      sha256 "d125db48587dd021559b602c5baa5d5e8816838dba71c93bcfef1fd1b1498154"

      define_method(:install) do
        bin.install "runner-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v2.4.1/runner-guard_2.4.1_darwin_arm64.tar.gz"
      sha256 "b4714f3bec96ad5769d3a6c8b4da935a2bfe4982fb01f610d166da3e9462e465"

      define_method(:install) do
        bin.install "runner-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v2.4.1/runner-guard_2.4.1_linux_amd64.tar.gz"
      sha256 "b19348683198ea6503d50901c1601f4dc3c676dabb02db24f56cb1609c64393e"
      define_method(:install) do
        bin.install "runner-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v2.4.1/runner-guard_2.4.1_linux_arm64.tar.gz"
      sha256 "99a8153fecceb44516345a5a9acc2000c75654854e77163fc9b81457984d56eb"
      define_method(:install) do
        bin.install "runner-guard"
      end
    end
  end

  test do
    system "#{bin}/runner-guard", "--version"
  end
end
