# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RunnerGuard < Formula
  desc "CI/CD source-to-sink vulnerability scanner for GitHub Actions"
  homepage "https://github.com/Vigilant-LLC/runner-guard"
  version "2.4.2"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v2.4.2/runner-guard_2.4.2_darwin_amd64.tar.gz"
      sha256 "94818267ff44e621b994fb664855f3c224a7487d1d09ae57cfc9827b511a1730"

      define_method(:install) do
        bin.install "runner-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v2.4.2/runner-guard_2.4.2_darwin_arm64.tar.gz"
      sha256 "b4b796bf2b9d4a221a013871e5c285dd05e510e999a915c6f8738d7b0a2d6b04"

      define_method(:install) do
        bin.install "runner-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v2.4.2/runner-guard_2.4.2_linux_amd64.tar.gz"
      sha256 "cef98e47a8bc83db5d56558e53df9ac93e37a08cd736b3b584d74228c342d0fb"
      define_method(:install) do
        bin.install "runner-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/runner-guard/releases/download/v2.4.2/runner-guard_2.4.2_linux_arm64.tar.gz"
      sha256 "074941203e9818d9d82c74986be82295d3aa04c4b36d6a69e8154555d6b81b92"
      define_method(:install) do
        bin.install "runner-guard"
      end
    end
  end

  test do
    system "#{bin}/runner-guard", "--version"
  end
end
