# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vxpwngard < Formula
  desc "CI/CD source-to-sink vulnerability scanner for GitHub Actions"
  homepage "https://github.com/Vigilant-LLC/vxpwngard"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vigilant-LLC/vxpwngard/releases/download/v1.1.0/vxpwngard_1.1.0_darwin_amd64.tar.gz"
      sha256 "f92fb57d31e66a100e75548bcc96857826c332ef27db62c38d21528836a54b42"

      define_method(:install) do
        bin.install "vxpwngard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vigilant-LLC/vxpwngard/releases/download/v1.1.0/vxpwngard_1.1.0_darwin_arm64.tar.gz"
      sha256 "03bef6425369e8cbc0377abdee99ed0a26b69debb8176cbc76107b840b6975f6"

      define_method(:install) do
        bin.install "vxpwngard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/vxpwngard/releases/download/v1.1.0/vxpwngard_1.1.0_linux_amd64.tar.gz"
      sha256 "2eeae0e8ac2f1c26060c6568a414b26f545b5b6ef479d9c6a5f9925a8bb7e7eb"
      define_method(:install) do
        bin.install "vxpwngard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vigilant-LLC/vxpwngard/releases/download/v1.1.0/vxpwngard_1.1.0_linux_arm64.tar.gz"
      sha256 "e3ee4d0b4567654f9539b7293429895bc47bc362b8ccc68beff64bfbb18f30c7"
      define_method(:install) do
        bin.install "vxpwngard"
      end
    end
  end

  test do
    system "#{bin}/vxpwngard", "version"
  end
end
